version: "3.1"

services:
  proxy-service:
    image: reverse-proxy:1
    build:
      context: ./nginx
    ports:
      - "443:443"
  api-service:
    image: probe:1
    build:
      context: ./api
    ports:
      - "8888:8888"
